### ISSUE TITLE
How to download large number of pictures?

### ISSUE THREAD

**Issue by salamatburj** [hardikvasa/google-images-download#94] opened 2018-05-07 17:11 UTC
Hello! Thank you for sharing code! I just want to learn how to download large amount of pictures. Although, you mentioned that we need selenium and google driver, I was not able to do it both in my mac and windows. I don't know how to set path for downloading large amount of pics. 

The error that I have for mac is: 
Looks like we cannot locate the path the 'chromedriver' (use the '--chromedriver' argument to specify the path to the executable.) or google chrome browser is not installed on your machine

Windows: Same in windows error and, it works only from cmd not from jupyter notebook. 
Error:
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-9-376f5952f3cb> in <module>()
----> 1 from google_images_download import google_images_download

ModuleNotFoundError: No module named 'google_images_download'

I think it would be great if you can share how to download more than 200 images, because ultimately we need much more for this course. Step by step explanation will be highly appreciated,

Thank you!
Salamat

**Comment by kevinkit** [comment] 2018-05-07 17:17
Can you show us how you set the chromedriver path?

salamatburj <notifications@github.com> schrieb am Mo., 7. Mai 2018, 19:11:

**Comment by salamatburj** [comment] 2018-05-08 00:28
I don't know how to set path for chrome driver. I just download it and open it via console.How to set path? Both in mac and windows?

**Comment by salamatburj** [comment] 2018-05-08 01:50
Problem solved! 
This is the way it is solved. After carefully reading documentation (mia culpa):
1) pip install selenium
2) download chrome driver, copy path e.g, ('C:\Users\Downloads\chromedriver')
3) Now we just need to add "chromedriver": 'C:\\Users\\Downloads\\chromedriver' to command. The code will look like this:
```
from google_images_download import google_images_download
response = google_images_download.googleimagesdownload()   #class instantiation

arguments = {"keywords":"Polar bears,baloons,Beaches","limit":2000,"print_urls":True,"chromedriver":chromedriver}   #creating list of arguments
response.download(arguments)
```

**Comment by hardikvasa** [comment] 2018-05-12 23:49
Glad that the issue is now resolved @salamatburj 
I have added some clarification in the docs around the chromedriver path for windows OS.

closing this issue now.

**Closed by hardikvasa** 2018-05-12 23:49 UTC
Labels: Error Reporting, command-line-query
