### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by reyanshmishra** [hardikvasa/google-images-download#48] opened 2018-03-10 18:31 UTC
is pagination possible?

**Comment by hardikvasa** [comment] 2018-03-11 00:12
@reyanshmishra can you please elaborate on your use case and where would you need pagination? 
Do you mean pagination in the output result printed on the console? If yes, then pagination is not possible for now.

**Comment by reyanshmishra** [comment] 2018-03-11 03:47
I am trying to create an image search API for google images(for private use) and right now Google returns only 100 results in one request. Is it possible to go after 100 images? As they are using ajax to fetch images (I guess) when we scroll.

**Comment by hardikvasa** [comment] 2018-03-11 06:52
@reyanshmishra this is a duplicate of #7 . This is definitely possible using selenium webdriver! :-)

**Closed by hardikvasa** 2018-03-11 06:52 UTC
Labels: duplicate

**Comment by reyanshmishra** [comment] 2018-03-11 07:16
ohh I am sorry I didn't see that one.

**Comment by hardikvasa** [comment] 2018-03-19 18:17
@reyanshmishra this feature has now been deployed. Now it gets all the images that are returned by the google image search. Tested on Windows and Mac and works fine. Linux testing pending.
