### ISSUE TITLE
Invalid character u'\x80'

### ISSUE THREAD

**Issue by amolchanov86** [hardikvasa/google-images-download#118] opened 2018-06-19 22:50 UTC
Image URL: http://%D0%B0%D1%80%D1%85%D1%81%D1%82%D1%80%D0%B0%D1%82%D0%B5%D0%B3%D0%B8%D1%8F.%D1%80%D1%84/images/metody/mc8/Images/RAS_57.jpg
Traceback (most recent call last):
  File "/opt/anaconda2/bin/googleimagesdownload", line 11, in <module>
    sys.exit(main())
  File "/opt/anaconda2/lib/python2.7/site-packages/google_images_download/google_images_download.py", line 888, in main
    paths = response.download(arguments)  #wrapping response in a variable just for consistency
  File "/opt/anaconda2/lib/python2.7/site-packages/google_images_download/google_images_download.py", line 843, in download
    items,errorCount,abs_path = self._get_all_items(raw_html,main_directory,dir_name,limit,arguments)    #get all image items and download images
  File "/opt/anaconda2/lib/python2.7/site-packages/google_images_download/google_images_download.py", line 709, in _get_all_items
    download_status,download_message,return_image_name,absolute_path = self.download_image(object['image_link'],object['image_format'],main_directory,dir_name,count,arguments['print_urls'],arguments['socket_timeout'],arguments['prefix'],arguments['print_size'],arguments['no_numbering'])
  File "/opt/anaconda2/lib/python2.7/site-packages/google_images_download/google_images_download.py", line 566, in download_image
    response = urlopen(req, None, timeout)
  File "/opt/anaconda2/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/anaconda2/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/opt/anaconda2/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/opt/anaconda2/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/opt/anaconda2/lib/python2.7/urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/opt/anaconda2/lib/python2.7/urllib2.py", line 1195, in do_open
    h.request(req.get_method(), req.get_selector(), req.data, headers)
  File "/opt/anaconda2/lib/python2.7/httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "/opt/anaconda2/lib/python2.7/httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "/opt/anaconda2/lib/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/opt/anaconda2/lib/python2.7/httplib.py", line 882, in _send_output
    self.send(msg)
  File "/opt/anaconda2/lib/python2.7/httplib.py", line 844, in send
    self.connect()
  File "/opt/anaconda2/lib/python2.7/httplib.py", line 821, in connect
    self.timeout, self.source_address)
  File "/opt/anaconda2/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/opt/anaconda2/lib/python2.7/encodings/idna.py", line 164, in encode
    result.append(ToASCII(label))
  File "/opt/anaconda2/lib/python2.7/encodings/idna.py", line 76, in ToASCII
    label = nameprep(label)
  File "/opt/anaconda2/lib/python2.7/encodings/idna.py", line 38, in nameprep
    raise UnicodeError("Invalid character %r" % c)
UnicodeError: Invalid character u'\x80'

**Comment by piotrex** [comment] 2018-06-23 11:17
I had proble with Polish diacritics, solved them in #114 . Maybe my modifications will solve ur errors too?

**Comment by hardikvasa** [comment] 2018-08-18 20:53
can you give me the query you used? I am able to reproduce this on the single_image() (opened an issue for that #147 ) but from the error stack trace it looks like you are getting this from download() method. Ideally it should have been caught by `UnicodeEncodeError` or `URLError` error handling block.

I tried the base URL: http://xn--80aajhq8bahjc2a2k.xn--p1ai/images/metody/mc8/Images/RAS_57.jpg

but i am still not able to repro the behavior.

**Comment by hardikvasa** [comment] 2018-08-25 19:12
Resolving this for now. Feel free to re-open the issue with additional information if the issue still persist. If the issue is reproducible, a complete query would be great to understand the root cause.

**Closed by hardikvasa** 2018-08-25 19:12 UTC
Labels: Error Reporting, pending-info
