### ISSUE TITLE
x-raw-image

### ISSUE THREAD

**Issue by enricopal** [hardikvasa/google-images-download#189] opened 2018-11-19 10:30 UTC
Hello,
I am using googleimagesdownload to get the URLs of images found on google.
I am using the CLI from within python and saving the printed URLs:

```
import subprocess
result = {'label': 'The Elements of Moral Philosophy', 'author': 'James Rachels'}
item_type = 'book'
out = subprocess.check_output(["googleimagesdownload", "--keywords", "\"%s %s %s\"" % (result['label'].replace(',',''), item_type, result['author']), "--print_urls", "-l", "1"])
url = out.decode('utf-8').split('\n')[4].replace('Image URL: ','') 
```

This works fine in general, but sometimes I get some weird results such as: x-raw-image:///c2cd85e815606ceef9f9926580a481686218ff8f1979e26816d1ba45f9eedeaa
which do not even seem to be URLs, they do not point to any image.

Does anyone have a clue where these results come from?
Thanks.
ENrico

**Comment by hardikvasa** [comment] 2019-04-23 05:06
@enricopal the above example you provided works when i test it on my end (mac, python2/3). Do you see the mentioned behavior in the example provided? or do you unexpected image result with a different keyword? Basically i am not able to reproduce this issue on my end and additional info would help me find out if there is any edge case scenario here.

**Comment by hardikvasa** [comment] 2019-05-14 00:40
This is now resolved in https://github.com/hardikvasa/google-images-download/commit/cf5ff4876b8384ef0d92e68b66fa648e494d2640

closing the issue.

**Closed by hardikvasa** 2019-05-14 00:40 UTC
Labels: pending-info, question
