### ISSUE TITLE
Can just save the url from images

### ISSUE THREAD

**Issue by dariodipa** [hardikvasa/google-images-download#151] opened 2018-08-27 16:15 UTC
Can just save the url from images ? Dont donwload.

**Comment by Beastjdhr** [comment] 2018-09-03 01:31
Hello, I would like to solve this issue. Can you be more specific about what the problem is?

**Comment by hardikvasa** [comment] 2018-11-04 09:00
@dariodipa @Beastjdhr this was added in #169 

Closing this issue.

**Closed by hardikvasa** 2018-11-04 09:00 UTC
