### ISSUE TITLE
>100 images on linux OS

### ISSUE THREAD

**Issue by freekeys** [hardikvasa/google-images-download#56] opened 2018-03-27 07:06 UTC
Hello, loving this program - so useful, thanks for creating it!

I am having trouble setting it up to >100 issues. I installed via CLI and ran setup.py, so am assuming based on your instructions that Selenium is installed. I also followed the geckodriver instructions and that seems to have been successful. I'm running Linux Mint. Any support would be much appreciated!

```
$ googleimagesdownload -k "Siamese cat, Domestic cat" -l 199 -o "cat images" -f jpg

Item no.: 1 --> Item name = Siamese cat
Evaluating...
Starting Download...


Unfortunately all 199 could not be downloaded because some images were not downloadable. 0 is all we got for this search filter!

Item no.: 2 --> Item name =  Domestic cat
Evaluating...
Starting Download...


Unfortunately all 199 could not be downloaded because some images were not downloadable. 0 is all we got for this search filter!

Everything downloaded!
Total Errors: 0

Total time taken: 0.14542031288146973 Seconds
```

**Comment by hardikvasa** [comment] 2018-03-27 07:20
@freekeys thanks for your feedback :-)

yes, as you might have read in #53 , this is a known issue with Linux OS but works fine on Windows and OS X. I will add this information in the documentation. I will also try implementing the algo using chromedriver instead of geckodriver. But for now this is a won't fix issue.

Closing this issue for now. Feel free to post back if you found a workaround/solution to the geckodriver issue on Linux!

**Comment by freekeys** [comment] 2018-03-27 09:34
Thanks @hardikvasa!

**Comment by hardikvasa** [comment] 2018-03-28 07:05
was working with a sample/dummy code using chromedriver (and chrome browser) to download all the images returned by google search and that seems to work on linux, mac and windows. Let me keep this issue open until i do some more tests and merge it in this repo... :-)

**Comment by hardikvasa** [comment] 2018-03-30 08:01
Thanks @jaredjohansen for the feedback.

@jaredjohansen @freekeys the script is now updated to use chromedriver (with chrome browser) instead of geckodriver (with firefox browser).

I have successfully tested this script on **Windows, Mac, Linux CentOs and Ubuntu** and works perfectly fine. I could download 750+ images per keyword (everything that google returns).

You can follow the one time installation guide of chromedriver and chrome browser in the troubleshooting section of the documentation. Do let me know if this works for you.

**Comment by andronovhopf** [comment] 2018-03-31 20:49
@hardikvasa I am trying this but still not working for me- I have chromedriver (v2.9, latest version) in the same directory where I am calling googleimagesdownload. I'm doing 

`googleimagesdownload --keywords "cute" --limit 200 --chromedriver "./chromedriver"`

And then I get the error 
`Looks like we cannot locate the path the 'chromedriver'. Please use the '--chromedriver' argument to specify the path to the executable.`

It get the same error if I call it at a different location-
`googleimagesdownload --keywords "cute" --limit 200 --chromedriver "/usr/local/bin/chromedriver"
`

**Comment by hardikvasa** [comment] 2018-03-31 20:56
@andronovhopf what linux OS are you running this from?

this could be due to various reasons:
* If the path is correct but the `chromedriver` file does not have execute permission
* can you try with an absolute path `/usr/local/bin/chromedriver` instead of a relative path? (should not matter but just for testing purposes)
* you do not have chrome browser installed in your system. In that case please look into the troubleshooting guide for links to install google chrome stable version

**Comment by andronovhopf** [comment] 2018-03-31 22:24
I’m running Ubuntu (xenial).

I’ll check out the permissions on the chrome driver- I got the same error using an absolute path, and I definitely have chrome browser installed on the system.

**Comment by andronovhopf** [comment] 2018-03-31 22:32
Yep it's in my directory and permissions look good

```
eobrien@picket:~$ ls -la
total 61016
drwxr-xr-x 61 eobrien eobrien     4096 Mar 31 13:39 .
drwxr-xr-x  4 root    root        4096 Jun 21  2017 ..
-rwxr-xr-x  1 eobrien root    19354520 Dec 16  2013 chromedriver

```

Tried the following
` sudo googleimagesdownload  --keywords "cute" --limit 200 --chromedriver "/home/eobrien/chromedriver"`

and

` googleimagesdownload  --keywords "cute" --limit 200 --chromedriver "./chromedriver"`

Failure :/

**Comment by hardikvasa** [comment] 2018-03-31 22:40
@andronovhopf thanks for the info. would you mind running the below command again to see if it updates to a stable version?

`sudo apt-get install google-chrome-stable`

This error could only be thrown if either the chromedriver was not found or the chrome browser was not found. This does not look to me like the issue is with chromedriver.

Did you happen to download the latest version of chromedriver (2.37) ?

**Comment by hardikvasa** [comment] 2018-03-31 22:59
@andronovhopf 

I did spin up an EC2 instance: ubuntu-xenial-16.04-amd64-server-20180306 (ami-4e79ed36)

And then i followed the exact same steps as mentioned in the accepted answer here to download google-chrome-stable
https://askubuntu.com/questions/510056/how-to-install-google-chrome

and then i used your query and it worked perfectly fine.

**Comment by andronovhopf** [comment] 2018-04-02 16:31
Got it! Now it's working. I had to make sure I had chromedriver 2.37, and
then it worked. I must have had a different version.

**Comment by hardikvasa** [comment] 2018-04-02 17:33
Sounds good! Closing this issue since this feature has been tested and it works on all major OS.

**Closed by hardikvasa** 2018-04-02 17:33 UTC
Labels: feature-request

**Comment by jaredjohansen** [comment] 2018-04-02 20:45
Just tested it on my machine.  Works for me too!  Thanks hardikvasa!

**Comment by xxllp** [comment] 2018-04-30 08:55
I have get fine  at first .but get the same error today

**Comment by xxllp** [comment] 2018-04-30 08:56
Unfortunately all 250 could not be downloaded because some images were not downloadable. 100 is all we got for this search filter!

**Comment by hardikvasa** [comment] 2018-04-30 15:38
@xxllp this could be because the qury that you used, Google image search only returned 100 images. Could you search on Google images page directly to see if that's true?
