### ISSUE TITLE
related_images download failed, and I have resolved this bug.

### ISSUE THREAD

**Issue by FieldRen** [hardikvasa/google-images-download#153] opened 2018-09-06 09:16 UTC
I used to download a ton of images related to my keyword by adding '--related_images' or '-ri' in my query. and it worked very well. But recently, it don't work, it just downloads images from my keywords, no any related images.

I have been tossing for a long time. Finally, I resolved this bug! It seems that google has updated its html format. And you just need to find 'get_next_tab(self,s)' function and modify 3 lines code. Or you can copy and replace the function below 

```
def get_next_tab(self,s):
    start_line = s.find('class="dtviD"')#class="ZO5Spb"
    if start_line == -1:  # If no links are found then give an error!
        end_quote = 0
        link = "no_tabs"
        return link,'',end_quote
    else:
        start_line = s.find('class="dtviD"')#class="ZO5Spb"
        start_content = s.find('href="', start_line + 1)
        end_content = s.find('">', start_content + 1)
        url_item = "https://www.google.com" + str(s[start_content+6:end_content])
        url_item = url_item.replace('&amp;', '&')
        start_line_2 = s.find('class="dtviD"')#class="ZO5Spb"
        start_content_2 = s.find(':', start_line_2 + 1)
        end_content_2 = s.find('"', start_content_2 + 1)
        url_item_name = str(s[start_content_2 + 1:end_content_2])
        return url_item,url_item_name,end_content
```

**Comment by jimgros** [comment] 2018-11-03 13:43
Hi,
I noticed the same thing. Thanks for sharing.  
I had the same problem and it solved it perfectly.

I would like to add to your changes something else.
I noticed that after your changes, the url_item needs to be modified as well.

So after the line nr 229 (where you modified the last instance of `"dtviD"`) I would change the lines of code to the following.
```
start_content_2 = s.find(':', start_line_2 + 1)
end_content_2 = s.find('usg=', start_content_2 + 1) - 20
url_item_name = str(s[start_content_2 + 1:end_content_2])
url_item_name = url_item_name.replace(',g_1:',' ')
url_item_name = url_item_name.replace('+',' ')
```

**Comment by hardikvasa** [comment] 2018-11-04 09:13
#154 was merged. The issue is resolved and the related_images work fine. However @jimgros you pointed that out right for the first issue you mentioned, can you open a PR for it? Closing this issue.

**Closed by hardikvasa** 2018-11-04 09:13 UTC
Labels: Error Reporting, bug

**Comment by jimgros** [comment] 2018-11-04 11:50
Done
(that was my first PR :P )
