### ISSUE TITLE
HTTP Error 503: Service Unavailable

### ISSUE THREAD

**Issue by BigRedT** [hardikvasa/google-images-download#165] opened 2018-10-14 23:49 UTC
The script worked great for upto ~28000 images and then I started getting `HTTP Error 503: Service Unavailable`. Restarting the script after a day or two downloaded another ~32000 images before throwing the `503` error again. 

Couldn't exactly figure out the cause or fix for this issue. Maybe there is a limit to how many images google allows you to download? If so, is there a way to get authorization for more?

**Comment by macro-dadt** [comment] 2018-10-24 07:16
I fixed it here https://github.com/macro-dadt/google-images-download/blob/master/google_images_download/google_images_download.py

**Comment by hardikvasa** [comment] 2018-11-04 09:32
@BigRedT can you give me the complete query that you were using? Were the images skipped on getting 503s or did the script break? If it is latter, I will need the query to reproduce the issue from my end.

**Comment by BigRedT** [comment] 2018-11-04 13:32
@hardikvasa it wasn't a single query. I was executing multiple single-word queries in parallel using `starmap` function in the python `multiprocessing` module and downloading 20 images per query. Those 60000 images actually correspond to 3000 queries, which actually might be the limit on free queries allowed by Google per user per month. 

Here are some snippets from my parallelized implementation. Each process would call the following function with a different word:
```python
def downloader(word,args):
    response = google_images_download.googleimagesdownload()
    search_arguments = {
        'keywords': word,
        'limit': args.images_per_word,
        'safe_search': True,
        'output_directory': args.outdir,
        'usage_rights': 'labeled-for-noncommercial-reuse-with-modification',
        'color_type': 'full-color',
        'type': 'photo',
    }
    print('-'*80)
    print(f'Downloading images for word: {word}')
    print('-'*80)
    absolute_image_paths = response.download(search_arguments)[word]
```

The launch code looks like:
```python 
def main():
    args = parser.parse_args()
    
    # Create output directory if it doesn't exist
    # Results of queries are saved in subdirectories of this output directory
    io.mkdir_if_not_exists(args.outdir)
    print(args.outdir)

    # Load a dict where the keys are the words to be queried in Google
    vocab = io.load_json_object(args.vocab_json)
    vocab_list = list(vocab.keys())
    with Pool(40) as p:
        p.starmap(downloader, product(vocab_list,[args]))
```

**Comment by rajexp** [comment] 2018-11-25 21:10
I am also struck with the same error. I have a script running every 10 minutes to fetch for a single image each for different URLs. I successfully downloaded for 4500 odd images but it is continuously giving me error on the server machine.
I am in a dire need for a workaround.

**Comment by hardikvasa** [comment] 2019-05-07 15:02
Yea seems to be like server is throttling on the request rate. @BigRedT @rajexp can you give me a complete error stack trace if you still have it? That will help me build a custom retry mechanism within the library to avoid failures.

**Comment by hardikvasa** [comment] 2019-05-16 18:50
Closing this thread for now. let me know if this issue pops up again and i will investigate it further :)

**Closed by hardikvasa** 2019-05-16 18:50 UTC
Labels: error-reporting, pending-info
