### ISSUE TITLE
http.client error when downloading certain images

### ISSUE THREAD

**Issue by xiapoy** [hardikvasa/google-images-download#83] opened 2018-04-19 15:41 UTC
Hello,

I am using your script to download some images and have the following error that blocks the downloads at a certain image:

```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/http/client.py", line 546, in _get_chunk_left
    chunk_left = self._read_next_chunk_size()
  File "/usr/local/lib/python3.6/http/client.py", line 513, in _read_next_chunk_size
    return int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/http/client.py", line 563, in _readall_chunked
    chunk_left = self._get_chunk_left()
  File "/usr/local/lib/python3.6/http/client.py", line 548, in _get_chunk_left
    raise IncompleteRead(b'')
http.client.IncompleteRead: IncompleteRead(0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/googleimagesdownload", line 11, in <module>
    load_entry_point('google-images-download==2.0.4', 'console_scripts', 'googleimagesdownload')()
  File "/usr/local/lib/python3.6/site-packages/google_images_download-2.0.4-py3.6.egg/google_images_download/google_images_download.py", line 784, in main
  File "/usr/local/lib/python3.6/site-packages/google_images_download-2.0.4-py3.6.egg/google_images_download/google_images_download.py", line 742, in download
  File "/usr/local/lib/python3.6/site-packages/google_images_download-2.0.4-py3.6.egg/google_images_download/google_images_download.py", line 631, in _get_all_items
  File "/usr/local/lib/python3.6/site-packages/google_images_download-2.0.4-py3.6.egg/google_images_download/google_images_download.py", line 540, in download_image
  File "/usr/local/lib/python3.6/http/client.py", line 456, in read
    return self._readall_chunked()
  File "/usr/local/lib/python3.6/http/client.py", line 570, in _readall_chunked
    raise IncompleteRead(b''.join(value))
http.client.IncompleteRead: IncompleteRead(87522 bytes read)
```

Also, thanks for sharing this awesome tool!

**Comment by jashshopin** [comment] 2018-04-21 18:06
Facing a similar error as well.

**Comment by hardikvasa** [comment] 2018-04-21 18:31
@xiapoy @jashshopin could you provide me with a sample query for which you are seeing this error? I would like to reproduce this on my end and at the very least add some exception handling.

**Comment by xxllp** [comment] 2018-04-28 07:33
@hardikvasa I face the same error ,just key word  like "刘诗诗" 

> 
Completed Image ====> 230. liics3j4haa9.jpg
IOError on an image...trying next one... Error: timed out
Completed Image ====> 231. 112154.34159403_620x620.jpg
Completed Image ====> 232. cs7pjh-b_400x400.jpg
Completed Image ====> 233. phpztsmx6.jpg
Completed Image ====> 234. 20160321014734759.jpg
Completed Image ====> 235. 134589840.jpg
Completed Image ====> 236. 732853c11939cfd68fa0666751a9cf70.jpg
Completed Image ====> 237. 20170415024326944.jpg
Completed Image ====> 238. 6d0dcd715752bfb8747dcfd359baf1118069e3dc_size26_w473_h449.jpeg
Traceback (most recent call last):
  File "/usr/local/bin/googleimagesdownload", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/google_images_download/google_images_download.py", line 784, in main
    response.download(arguments)
  File "/usr/local/lib/python3.5/dist-packages/google_images_download/google_images_download.py", line 742, in download
    items,errorCount = self._get_all_items(raw_html,main_directory,dir_name,limit,arguments)    #get all image items and download images
  File "/usr/local/lib/python3.5/dist-packages/google_images_download/google_images_download.py", line 631, in _get_all_items
    download_status,download_message,return_image_name = self.download_image(object['image_link'],object['image_format'],main_directory,dir_name,count,arguments['print_urls'],arguments['socket_timeout'],arguments['prefix'],arguments['print_size'])
  File "/usr/local/lib/python3.5/dist-packages/google_images_download/google_images_download.py", line 540, in download_image
    data = response.read()
  File "/usr/lib/python3.5/http/client.py", line 461, in read
    s = self._safe_read(self.length)
  File "/usr/lib/python3.5/http/client.py", line 609, in _safe_read
    raise IncompleteRead(b''.join(s), amt)
http.client.IncompleteRead: IncompleteRead(13049 bytes read, 22186 more expected)

**Comment by luzer** [comment] 2018-05-07 16:15
same here

**Comment by hardikvasa** [comment] 2018-05-16 04:37
Folks, although i could not reproduce this issue on my end, I have added some exception handling to avoid it throwing an unhandled exception.

Do let me know if this resolves the issue.

**Comment by hardikvasa** [comment] 2018-05-29 23:14
Closing this for now. Do let me know if this error re-occurs.

**Closed by hardikvasa** 2018-05-29 23:14 UTC
Labels: Error Reporting
